START /WAIT "title" "C:\Program Files\RAMAS Multispecies 6\SpatialData.exe" binary10_0.ptc /RUN=YES /TEX
START /WAIT "title" "C:\Program Files\RAMAS Multispecies 6\SpatialData.exe" cont10_0.ptc /RUN=YES /TEX /DAT=C:/Users/cb3452/OneDrive-DrexelUniversity/bbland/bbland-github/data/n10
START /WAIT "title" "C:\Program Files\RAMAS Multispecies 6\Habdyn.exe" both10_0.pdy /RUN=YES /TEX
START /WAIT "title" "C:\Program Files\RAMAS Multispecies 6\SpatialData.exe" both10_0.mp /RUN=YES /TEX
